# Get editor completions based on the config schema

#####
#This file must be in $HOME/.config/starship.toml
# After add the following code in $HOME/.zshrc
# eval "$(starship init zsh)"
# You can find emoji here https://emojipedia.org/baby-bottle
#####

"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[time] #the time module
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '+2'
time_range = '00:00:00-23:59:59'

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](yellow)"

[line_break]
disabled = false

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style) '
style = 'bold purple'
symbol = 'ğŸŒ± '
truncation_length = 8
truncation_symbol = '...'
ignore_branches = []

[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = 'user: [$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

[os]
format = "on [($name)]($style)"
style = "bold blue"
disabled = true


[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = true


[kubernetes]
format = 'on [â›µ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "ğŸ’” " },
]


[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

